version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix
    versions:
    - 1.5.7
  - dependency-name: sentry
    versions:
    - 8.0.4
  - dependency-name: bamboo_smtp
    versions:
    - 3.0.0
